### ISSUE TITLE
Invalid TOML when appending tables or documents to arrays

### ISSUE THREAD

**Issue by jeremander** [python-poetry/tomlkit#360]
Python version: 3.11.0
tomlkit version: 0.12.4

The following procedures give different TOML strings when I would expect them to be the same.

```python
import tomlkit as tk

def make_doc(val):
    doc = tk.document()
    arr = tk.array()
    arr.append(val)
    doc['a'] = arr
    return doc

# regular dict
dict_val = {'b': {}}

# same dict, but as a table
tbl_val = tk.table()
tbl_val['b'] = {}
assert tbl_val == dict_val

# same dict, but as a document
doc_val = tk.document()
doc_val['b'] = {}
assert doc_val == dict_val

print(tk.dumps(make_doc(dict_val)))
a = [{b = {}}]

print(tk.dumps(make_doc(tbl_val)))
a = [[b]
]

print(tk.dumps(make_doc(doc_val)))
a = [{b = }]
```

Only the first of these is valid TOML.  It's surprising the results are different given they all have the same content.

The issues persist even if I change `arr.append(val)` to `arr.append(dict(val))`, or if I switch from `{'b': {}}` to a version without the empty dict, `{'b': {'c': 1}}`.

**Comment by frostming** [comment]
In TOMLKit, elements have not only semantic meaning but also structural meaning.

For example, `array` means a inline array wrapped by `[]`, different from an array of table(table with `[[name]]` header)
and `table` means a regular TOML table, not inline table. They can't replace each other, so just avoid this kind of usage.

By creating document with these TOMLkit elements, you are manipulating the format and structure, you are responsible to choose the right elements. Otherwise if you don't care about the formats, just use plain python objects.
